const mongoose=require('mongoose');
const sherlockSchema=new mongoose.Schema({
    "7Cups":{
        type:String
    },
    "9GAG":{
        type:String,
    },
    "About.me":{
        type:String,
    },
    "Academia.edu":{
        type:String,
    },
    "AllMyLinks":{
        type:String,
    },
    "AnilList":{
        type:String,
    },
    "AskFM":{
        type:String,
    },
    "Audiojungle":{
        type:String,
    },
    "BLIP.fm":{
        type:String,
    },
    "Blogger":{
        type:String,
    },
    "CGTrader":{
        type:String,
    },
    "Chess":{
        type:String,
    },
    "Codecademy":{
        type:String,
    },
    "Codechef":{
        type:String,
    },
    "Codewars":{
        type:String,
    },
    "Crowdin":{
        type:String,
    },
    "Cults3D":{
        type:String,
    },
    "DEV Community":{
        type:String,
    },
    "DeviantART":{
        type:String,
    },
    "Discuss.Elastic.co":{
        type:String,
    },
    "Disqus":{
        type:String,
    },
    "Docker Hub":{
        type:String,
    },
    "Dribble":{
        type:String,
    },
    "Enjin":{
        type:String,
    },
    "F3.cool":{
        type:String,
    },
    "Facebook":{
        type:String,
    },
    "Fiverr":{
        type:String,
    },
    "Flickr":{
        type:String,
    },
    "Flipboard":{
        type:String,
    },
    "Freelancer":{
        type:String,
    },
    "Freesound":{
        type:String,
    },
    "GaiaOnline":{
        type:String,
    },
    "Genius(Artists)":{
        type:String,
    },
    "Genius(Users)":{
        type:String,
    },
    "Giphy":{
        type:String,
    },
    "Github":{
        type:String,
    },
    "GitLab":{
        type:String,
    },
    "Grailed":{
        type:String,
    },
    "Gravatar":{
        type:String,
    },
    "Gumroad":{
        type:String,
    },
    "Gutefrage":{
        type:String,
    },
    "HackerEarth":{
        type:String,
    },
    "HackerNews":{
        type:String,
    },
    "HackerOne":{
        type:String,
    },
    "HackerRank":{
        type:String,
    },
    "Hashnode":{
        type:String,
    },
    "Houzz":{
        type:String,
    },
    "HubPages":{
        type:String,
    },
    "IFTTT":{
        type:String,
    },
    "Imgur":{
        type:String,
    },
    "Instructables":{
        type:String,
    },
    "Issuu":{
        type:String,
    },
    "Kaggle":{
        type:String,
    },
    "Keybase":{
        type:String,
    },
    "Kik":{
        type:String,
    },
    "Launchpad":{
        type:String,
    },
    "Leetcode":{
        type:String,
    },
    "Letterboxd":{
        type:String,
    },
    "Lichess":{
        type:String,
    },
    "Medium":{
        type:String,
    },
    "Minecraft":{
        type:String,
    },
    "MixCloud":{
        type:String,
    },
    "MyAnimeList":{
        type:String,
    },
    "Myspace":{
        type:String,
    },
    "Naver":{
        type:String,
    },
    "Needrom":{
        type:String,
    },
    "PSNProfiles.com":{
        type:String,
    },
    "Pastebin":{
        type:String,
    },
    "Patreon":{
        type:String,
    },
    "Pokemon Showdown":{
        type:String,
    },
    "PromoDJ":{
        type:String,
    },
    "PyPi":{
        type:String,
    },
    "Quizlet":{
        type:String,
    },
    "Redbubble":{
        type:String,
    },
    "Replit.com":{
        type:String,
    },
    "ReverbNation":{
        type:String,
    },
    "Rumble":{
        type:String,
    },
    "Scratch":{
        type:String,
    },
    "Scribd":{
        type:String,
    },
    "Sketchfab":{
        type:String,
    },
    "Slack":{
        type:String,
    },
    "Slashdot":{
        type:String,
    },
    "Slideshare":{
        type:String,
    },
    "Smule":{
        type:String,
    },
    "SoundCloud":{
        type:String,
    },
    "SourceForge":{
        type:String,
    },
    "Speedrun.com":{
        type:String,
    },
    "Splice":{
        type:String,
    },
    "Strava":{
        type:String,
    },
    "TETR.IO":{
        type:String,
    },
    "Telegram":{
        type:String,
    },
    "Tenor":{
        type:String,
    },
    "ThemeForest":{
        type:String,
    },
    "TradingView":{
        type:String,
    },
    "TrashboxRU":{
        type:String,
    },
    "Trello":{
        type:String,
    },
    "TryHackMe":{
        type:String,
    },
    "Twitch":{
        type:String,
    },
    "Twitter":{
        type:String,
    },
    "Typeracer":{
        type:String,
    },
    "Ultimate-Guitar":{
        type:String,
    },
    "Unsplash":{
        type:String,
    },
    "VSCO":{
        type:String,
    },
    "Vero":{
        type:String,
    },
    "Vimeo":{
        type:String,
    },
    "Warrior Forum":{
        type:String,
    },
    "Wattpad":{
        type:String,
    },
    "We Hear It":{
        type:String,
    },
    "Wikidot":{
        type:String,
    },
    "Windy":{
        type:String,
    },
    "WordPress":{
        type:String,
    },
    "WordPressOrg":{
        type:String,
    },
    "Wordnik":{
        type:String,
    },
    "YouNow":{
        type:String,
    },
    "YouPic":{
        type:String,
    },
    "aminoapp":{
        type:String,
    },
    "couchsurfing":{
        type:String,
    },
    "freecodecamp":{
        type:String,
    },
    "geocaching":{
        type:String,
    },
    "gfycat":{
        type:String,
    },
    "hackster":{
        type:String,
    },
    "interpals":{
        type:String,
    },
    "koo":{
        type:String,
    },
    "last.fm":{
        type:String,
    },
    "metacritic":{
        type:String,
    },
    "minds":{
        type:String,
    },
    "nairaland.com":{
        type:String,
    },
    "osu!":{
        type:String,
    },
    "zoomit":{
        type:String,
    }

   
})

const sherlockModel=mongoose.model('sherlockModel',sherlockSchema);
module.exports=sherlockModel;